/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import bd.JogoDAO;
import java.io.File;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Jogo;

/**
 *
 * @author Unicesumar
 */
public class TelaInserirGames extends javax.swing.JFrame {

    Jogo j = new Jogo();
    
    public TelaInserirGames() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFAno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TFGenero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TFDev = new javax.swing.JTextField();
        BottonCarregarImagem = new javax.swing.JButton();
        BottonInserir = new javax.swing.JButton();
        BottonReiniciar = new javax.swing.JButton();
        BottonVoltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLTitulo.setBackground(new java.awt.Color(0, 255, 255));
        jLTitulo.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLTitulo.setText("INSERIR NOVO JOGO ");

        jLabel2.setFont(new java.awt.Font("Square721 BT", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nome:");

        TFNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Square721 BT", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Ano:");

        TFAno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Square721 BT", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Gênero:");

        TFGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Square721 BT", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Desenvolvedora:");

        TFDev.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TFDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDevActionPerformed(evt);
            }
        });

        BottonCarregarImagem.setBackground(new java.awt.Color(0, 102, 102));
        BottonCarregarImagem.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        BottonCarregarImagem.setForeground(new java.awt.Color(0, 255, 255));
        BottonCarregarImagem.setText("Carregar Imagem");
        BottonCarregarImagem.setBorderPainted(false);
        BottonCarregarImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BottonCarregarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonCarregarImagemActionPerformed(evt);
            }
        });

        BottonInserir.setBackground(new java.awt.Color(0, 102, 102));
        BottonInserir.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        BottonInserir.setForeground(new java.awt.Color(0, 255, 255));
        BottonInserir.setText("INSERIR");
        BottonInserir.setBorderPainted(false);
        BottonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonInserirActionPerformed(evt);
            }
        });

        BottonReiniciar.setBackground(new java.awt.Color(0, 102, 102));
        BottonReiniciar.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        BottonReiniciar.setForeground(new java.awt.Color(0, 255, 255));
        BottonReiniciar.setText("REINICIAR");
        BottonReiniciar.setBorderPainted(false);
        BottonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonReiniciarActionPerformed(evt);
            }
        });

        BottonVoltar.setBackground(new java.awt.Color(0, 102, 102));
        BottonVoltar.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        BottonVoltar.setForeground(new java.awt.Color(0, 255, 255));
        BottonVoltar.setText("VOLTAR");
        BottonVoltar.setBorderPainted(false);

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Square721 BT", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Imagem:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(BottonInserir))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BottonCarregarImagem)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BottonReiniciar)
                                .addGap(18, 18, 18)
                                .addComponent(BottonVoltar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addComponent(TFDev))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFGenero)
                            .addComponent(TFNome)
                            .addComponent(TFAno, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLTitulo)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BottonCarregarImagem)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BottonInserir)
                    .addComponent(BottonReiniciar)
                    .addComponent(BottonVoltar))
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottonCarregarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonCarregarImagemActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnValue = fc.showOpenDialog(null);
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File selectedFile = fc.getSelectedFile();
            
            try{
                j.setImagem(Files.readAllBytes(selectedFile.toPath()));
                JOptionPane.showMessageDialog(null,"Arquivo carregado com sucesso!");
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,"Erro ao carregar arquivo!");
            }
        }
    }//GEN-LAST:event_BottonCarregarImagemActionPerformed

    private void TFDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFDevActionPerformed

    private void BottonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonReiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BottonReiniciarActionPerformed

    private void BottonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonInserirActionPerformed
        if(!TFNome.getText().equals("")) {   
        j.setNome(TFNome.getText());
        j.setAno(Integer.parseInt(TFAno.getText()));
        j.setDesenvolvedor(TFDev.getText());
        j.setGenero(TFGenero.getText());
        
        JogoDAO jDAO = new JogoDAO();
        jDAO.insert(j);
        }else{
            JOptionPane.showMessageDialog(null, "Informe o nome do jogo!");
        }
            
    }//GEN-LAST:event_BottonInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInserirGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInserirGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInserirGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInserirGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInserirGames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottonCarregarImagem;
    private javax.swing.JButton BottonInserir;
    private javax.swing.JButton BottonReiniciar;
    private javax.swing.JButton BottonVoltar;
    private javax.swing.JTextField TFAno;
    private javax.swing.JTextField TFDev;
    private javax.swing.JTextField TFGenero;
    private javax.swing.JTextField TFNome;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
